"""The verifier: no number reaches a reader unless it matches the facts registry.

    python -m desk.verify                      # every memo in reports/memos/
    python -m desk.verify path/to/memo.md ...  # specific files
    python -m desk.verify --now 2026-10-05T00:00:00Z   # check freshness against a given clock

It reads any memo markdown, whether generated by desk.memo, written by an LLM,
or edited by a person, and fails (exit code 1) unless:

  1. every number in the text is a *claim* immediately followed by a citation
     `[^fact.id]`, e.g.  `371 bps[^liq.AAVE.slip_1m_bps]`;
  2. the cited id exists in facts.json;
  3. the unit written next to the number is the fact's unit ($ = usd, % = pct,
     bps, x, days; a bare number may cite a count, a statistic or days);
  4. the number is a correct rounding of the fact: it lies within half a unit
     of its last written digit (so 371 and 371.4 both match 371.385), and it
     carries at least 2 significant figures unless it is exact ("$1B" for
     $964M is rejected as too imprecise, "$1M" for a parameter of exactly
     $1,000,000 is fine);
  5. the fact is fresh: at most --max-lag-hours older than the newest data in
     the same registry (catches a stale-cache fallback mixed into a live run),
     and, for live registries or when --now is given, at most --max-age-hours
     older than the clock;
  6. the memo is bound to this registry (its header carries the sha256 of
     facts.json) and its Sources footnotes are exactly what the registry
     says (so nobody can quietly edit a source line);
  7. no banned language: guarantees, price targets, buy/sell recommendations,
     "risk-free" (except "risk-free rate"), spelled-out magnitudes such as
     "five million" that would dodge the number check.

The verifier fails closed: anything that looks like a number and is not a
verified claim is an error. A false alarm costs an edit; a false pass costs
credibility.

What it does NOT check (see ARCHITECTURE.md section 9): whether the prose
around a correct number says something true about it ("fees rose" when they
fell), whether the right fact was cited for the sentence's meaning, and
numbers written as small words ("three venues").
"""
from __future__ import annotations

import argparse
import json
import re
import sys
from dataclasses import asdict, dataclass, field
from datetime import datetime, timezone
from pathlib import Path

from desk.config import REPORTS_DIR, ROOT
from desk.facts import Fact, Registry, load_registry, parse_iso

DEFAULT_MAX_LAG_HOURS = 48.0
DEFAULT_MAX_AGE_HOURS = 48.0
MIN_SIG_FIGS = 2

# ---------------------------------------------------------------- grammar
FACT_ID = r"[A-Za-z0-9_.]+"
CITE_RE = re.compile(r"\[\^(?P<id>" + FACT_ID + r")\]")
TOKEN_RE = re.compile(r"\{\{\s*fact:(?P<id>[^}\s]+)\s*\}\}")
BROKEN_TOKEN_RE = re.compile(r"\{+\s*fact\s*:[^}\n]*\}*")      # any token-like leftover, even mangled
HEADER_RE = re.compile(r"<!--\s*desk-memo\s+symbol=(?P<symbol>\S+)\s+facts_sha256=(?P<sha>[0-9a-f]{64})\s*-->")
FOOTDEF_RE = re.compile(r"^\[\^(?P<id>" + FACT_ID + r")\]:(?P<body>.*)$")

CLAIM_RE = re.compile(
    r"(?<![A-Za-z0-9_.,$])"
    r"(?P<sign>[-+−])?"
    r"(?P<cur>\$)?"
    r"(?P<num>\d{1,3}(?:,\d{3})+(?:\.\d+)?|\d+(?:\.\d+)?)"
    r"(?:(?P<mag>bn|mn|[kKmMbBtT])(?![A-Za-z]))?"
    r"(?P<unit>\s?(?:%|percent\b|pct\b)|\s?(?:bps|bp|basis points?)\b|[x×](?![A-Za-z0-9])"
    r"|(?:\s|-)?(?:days?|d)\b)?"
    r"(?P<close>\*{1,2}|_{1,2})?"
    r"(?:\s?\[\^(?P<id>" + FACT_ID + r")\])?"
)
MAG = {"k": 1e3, "K": 1e3, "m": 1e6, "M": 1e6, "mn": 1e6, "b": 1e9, "B": 1e9, "bn": 1e9,
       "t": 1e12, "T": 1e12}

# spans that contain digits but are not claims: masked before scanning
EXEMPT_RES = [
    re.compile(r"\]\([^)\s]*\)"),                                   # markdown link targets
    re.compile(r"https?://\S+"),                                    # bare URLs
    re.compile(r"\b\d{4}-\d{2}-\d{2}(?:[T ]\d{2}:\d{2}(?::\d{2})?(?:\.\d+)?(?:Z|\s?UTC)?)?"),  # ISO dates
    re.compile(r"\b\d{2}:\d{2}(?::\d{2})?\s?UTC\b"),                # clock times
    re.compile(r"^\s*\d+[.)]\s", re.M),                             # ordered-list markers
    re.compile(r"^#{1,6}\s+(?:\d+\.)+\d*\s", re.M),                 # numbered headings "## 2. "
]

BANNED = [
    (r"\bguarantee[ds]?\b", "guarantee language"),
    (r"\brisk[- ]free\b(?!\s+rate)", '"risk-free" (only "risk-free rate" is allowed)'),
    (r"\b(?:price|fair[- ]value)\s+target\b|\btarget\s+price\b", "price target"),
    (r"\b(?:strong\s+)?(?:buy|sell|hold|accumulate|outperform|underperform)\s+(?:rating|recommendation|call|signal)\b",
     "recommendation"),
    (r"\brating\s*[:=]\s*(?:buy|sell|hold)\b", "recommendation"),
    (r"\bwe\s+(?:recommend|advise|suggest)\b|\brecommend(?:s|ed)?\s+(?:buying|selling|accumulating|shorting)\b",
     "recommendation"),
    (r"\b(?:should|must)\s+(?:buy|sell|accumulate|short|avoid)\b", "recommendation"),
    (r"\b(?:buy|sell)\s+(?:now|the\s+dip|before|it)\b", "recommendation"),
    (r"\b(?:undervalued|overvalued|cheap\s+relative|a\s+bargain)\b", "valuation call (the analyst's job, not the desk's)"),
    (r"\bwill\s+(?:rise|reach|hit|double|triple|moon|go\s+up|outperform|rally|recover)\b", "price prediction"),
    (r"\bto\s+the\s+moon\b|\bcan(?:not|'t)\s+lose\b|\bno[- ]brainer\b|\bsure\s+thing\b|\bno\s+downside\b",
     "promotional language"),
    (r"\b(?:thousand|million|billion|trillion)s?\b", "spelled-out magnitude (write digits and cite a fact)"),
]
BANNED_RES = [(re.compile(p, re.I), why) for p, why in BANNED]


# ---------------------------------------------------------------- results
@dataclass
class Issue:
    line: int
    kind: str          # uncited | unknown_fact | unit_mismatch | value_mismatch | imprecise | stale |
                       # banned | unrendered_token | no_header | wrong_registry | footnote | missing_footnote
    text: str
    detail: str


@dataclass
class MemoResult:
    path: str
    ok: bool = True
    n_claims: int = 0
    n_verified: int = 0
    cited_ids: list = field(default_factory=list)
    issues: list = field(default_factory=list)

    def add(self, line, kind, text, detail):
        self.issues.append(Issue(line, kind, text, detail))
        self.ok = False


# ---------------------------------------------------------------- canonical footnote
def unit_label(unit: str) -> str:
    return {"usd": "USD", "pct": "%", "bps": "bps", "x": "x", "days": "days", "count": "", "number": ""}[unit]


def footnote_definition(fact: Fact, reg: Registry) -> str:
    """The one allowed text of a Sources footnote. The renderer writes it; the verifier compares to it."""
    parts = []
    for sid in fact.source:
        if sid.startswith("group:"):
            parts.append(f"`{sid}` (see facts.json)")
        else:
            s = reg.sources.get(sid, {})
            where = f" (`{s['cache_file']}`)" if s.get("cache_file") else ""
            parts.append(f"{s.get('api', '?')} `{s.get('endpoint', '?')}`{where}")
    val = f"{fact.value:g}" if isinstance(fact.value, float) else str(fact.value)
    unit = unit_label(fact.unit)
    as_of = fact.as_of or "n/a (parameter)"
    return (f"[^{fact.id}]: `{fact.id}` = {val}{(' ' + unit) if unit else ''} | {fact.description} "
            f"| as of {as_of} | source: {'; '.join(parts)}")


# ---------------------------------------------------------------- core
def _mask(text: str, spans: list[tuple[int, int]]) -> str:
    chars = list(text)
    for a, b in spans:
        for i in range(a, b):
            if chars[i] != "\n":
                chars[i] = " "
    return "".join(chars)


def _claim_unit(m: re.Match) -> str | None:
    if m.group("cur"):
        return "usd"
    u = (m.group("unit") or "").strip().lstrip("-").lower()
    if not u:
        return None
    if u in ("%", "percent", "pct"):
        return "pct"
    if u.startswith("b"):
        return "bps"
    if u in ("x", "×"):
        return "x"
    return "days"


def _sig_figs(num: str) -> int:
    digits = num.replace(",", "").replace(".", "").lstrip("0")
    return len(digits)


def check_claim(m: re.Match, reg: Registry) -> tuple[str, str] | None:
    """Return (kind, detail) if the claim fails, None if it verifies."""
    fid = m.group("id")
    if not fid:
        return "uncited", "number has no [^fact.id] citation right after it"
    if fid not in reg:
        return "unknown_fact", f"'{fid}' is not in facts.json (fabricated or renamed id)"
    fact = reg[fid]
    cu = _claim_unit(m)
    compatible = {"usd": {"usd"}, "pct": {"pct"}, "bps": {"bps"}, "x": {"x"}, "days": {"days"},
                  None: {"count", "number", "days"}}[cu]
    if fact.unit not in compatible:
        shown = cu or "a bare number"
        return "unit_mismatch", f"written as {shown}, but {fid} is in {fact.unit}"
    num = m.group("num")
    mult = MAG.get(m.group("mag") or "", 1.0)
    sign = -1.0 if m.group("sign") in ("-", "−") else 1.0
    claimed = sign * float(num.replace(",", "")) * mult
    decimals = len(num.split(".")[1]) if "." in num else 0
    tol = 0.5 * 10 ** (-decimals) * mult
    diff = abs(claimed - float(fact.value))
    exact = diff <= 1e-9 * max(1.0, abs(float(fact.value)))
    if not exact and diff > tol * (1 + 1e-9):
        return "value_mismatch", (f"written {m.group(0).split('[')[0].strip()} = {claimed:g}, "
                                  f"registry has {fact.value:g} {fact.unit} (allowed rounding +/- {tol:g})")
    if not exact and _sig_figs(num) < MIN_SIG_FIGS:
        return "imprecise", f"{num} has fewer than {MIN_SIG_FIGS} significant figures for {fact.value:g}"
    return None


def check_freshness(fact: Fact, reg: Registry, max_lag_h: float, now: datetime | None,
                    max_age_h: float) -> str | None:
    if fact.as_of is None:
        return None                       # parameters do not age
    t = parse_iso(fact.as_of)
    newest = reg.meta.get("data_as_of")
    if newest:
        lag = (parse_iso(newest) - t).total_seconds() / 3600
        if lag > max_lag_h:
            return (f"{fact.id} was fetched {fact.as_of}, {lag:.0f}h before the newest data in the registry "
                    f"(limit {max_lag_h:g}h): a stale cache was mixed into this run")
    if now is not None:
        age = (now - t).total_seconds() / 3600
        if age > max_age_h:
            return f"{fact.id} was fetched {fact.as_of}, {age:.0f}h ago (limit {max_age_h:g}h)"
    return None


def verify_text(text: str, reg: Registry, *, path: str = "<memo>", max_lag_h: float = DEFAULT_MAX_LAG_HOURS,
                now: datetime | None = None, max_age_h: float = DEFAULT_MAX_AGE_HOURS,
                require_header: bool = True) -> MemoResult:
    res = MemoResult(path)
    line_of = lambda pos: text.count("\n", 0, pos) + 1

    # 1. header binds the memo to one registry
    hdr = HEADER_RE.search(text)
    if hdr is None:
        if require_header:
            res.add(1, "no_header", "", "missing '<!-- desk-memo symbol=... facts_sha256=... -->' header")
    elif hdr.group("sha") != reg.sha256:
        res.add(line_of(hdr.start()), "wrong_registry", hdr.group("sha")[:12],
                f"memo was rendered against facts.json {hdr.group('sha')[:12]}, not {reg.sha256[:12]}")

    # 2. split off the footnote definitions (Sources); they must be canonical
    body_lines, defs = [], {}
    for i, ln in enumerate(text.split("\n"), start=1):
        fm = FOOTDEF_RE.match(ln)
        if fm:
            defs[fm.group("id")] = (i, ln.rstrip())
            body_lines.append(" " * len(ln))
        else:
            body_lines.append(ln)
    body = "\n".join(body_lines)
    for fid, (i, ln) in defs.items():
        if fid not in reg:
            res.add(i, "unknown_fact", ln[:80], f"Sources entry for unknown fact '{fid}'")
        elif ln != footnote_definition(reg[fid], reg):
            res.add(i, "footnote", ln[:80], f"Sources entry for '{fid}' differs from the registry (edited by hand?)")

    # 3. leftover template tokens
    for tm in BROKEN_TOKEN_RE.finditer(body):
        res.add(line_of(tm.start()), "unrendered_token", tm.group(0), "template token was never rendered")

    # 4. mask exempt spans, then scan every number
    spans = [(hdr.start(), hdr.end())] if hdr else []
    for rx in EXEMPT_RES:
        spans += [(m.start(), m.end()) for m in rx.finditer(body)]
    spans += [(m.start(), m.end()) for m in BROKEN_TOKEN_RE.finditer(body)]
    scan = _mask(body, spans)
    cite_spans = [(m.start(), m.end()) for m in CITE_RE.finditer(scan)]
    in_cite = lambda p: any(a <= p < b for a, b in cite_spans)

    for m in CLAIM_RE.finditer(scan):
        if in_cite(m.start()):
            continue                      # digits inside a fact id, e.g. [^liq.AAVE.slip_1m_bps]
        res.n_claims += 1
        snippet = text[max(0, m.start() - 25): m.end() + 5].replace("\n", " ")
        failure = check_claim(m, reg)
        if failure is None:
            fid = m.group("id")
            stale = check_freshness(reg[fid], reg, max_lag_h, now, max_age_h)
            if stale:
                failure = ("stale", stale)
            elif fid not in defs:
                failure = ("missing_footnote", f"[^{fid}] has no Sources entry (run python -m desk.memo --render)")
        if failure:
            res.add(line_of(m.start()), failure[0], snippet.strip(), failure[1])
        else:
            res.n_verified += 1
            res.cited_ids.append(m.group("id"))

    # 5. banned language (anywhere in the body, including headings and tables)
    prose = _mask(body, [(hdr.start(), hdr.end())] if hdr else [])
    for rx, why in BANNED_RES:
        for bm in rx.finditer(prose):
            res.add(line_of(bm.start()), "banned", bm.group(0), why)

    res.cited_ids = sorted(set(res.cited_ids))
    res.issues.sort(key=lambda x: x.line)
    return res


# ---------------------------------------------------------------- CLI
def _collect(paths: list[str]) -> list[Path]:
    out = []
    for p in paths:
        p = Path(p)
        out += sorted(p.glob("*.md")) if p.is_dir() else [p]
    return out


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description="Verify that every number in a memo matches facts.json.")
    ap.add_argument("paths", nargs="*", default=[str(REPORTS_DIR / "memos")])
    ap.add_argument("--facts", default=str(REPORTS_DIR / "facts.json"))
    ap.add_argument("--report", default=str(REPORTS_DIR / "verification.json"),
                    help="where to write the JSON report ('-' to skip)")
    ap.add_argument("--max-lag-hours", type=float, default=DEFAULT_MAX_LAG_HOURS)
    ap.add_argument("--max-age-hours", type=float, default=DEFAULT_MAX_AGE_HOURS)
    ap.add_argument("--now", help="ISO time to check freshness against (default: the clock, for live registries)")
    ap.add_argument("--no-wall-clock", action="store_true", help="skip the age-vs-clock check")
    ap.add_argument("-q", "--quiet", action="store_true")
    args = ap.parse_args(argv)

    reg = load_registry(args.facts)
    if args.now:
        now = parse_iso(args.now)
    elif args.no_wall_clock or reg.meta.get("mode") == "snapshot":
        now = None     # a committed snapshot reproduces a past run; its age is known and intended
    else:
        now = datetime.now(timezone.utc)

    files = _collect(args.paths)
    if not files:
        print("verify: no memo files found", file=sys.stderr)
        return 1
    results = [verify_text(f.read_text(encoding="utf-8"), reg, path=_rel(f), max_lag_h=args.max_lag_hours,
                           now=now, max_age_h=args.max_age_hours) for f in files]
    ok = all(r.ok for r in results)

    report = {"ok": ok, "facts": _rel(Path(args.facts)), "facts_sha256": reg.sha256,
              "registry_mode": reg.meta.get("mode"), "data_as_of": reg.meta.get("data_as_of"),
              "wall_clock_checked_at": now.strftime("%Y-%m-%dT%H:%M:%SZ") if now else None,
              "limits": {"max_lag_hours": args.max_lag_hours, "max_age_hours": args.max_age_hours,
                         "min_sig_figs": MIN_SIG_FIGS},
              "memos": [{**{k: v for k, v in asdict(r).items() if k != "issues"},
                         "issues": [asdict(i) for i in r.issues]} for r in results]}
    if args.report != "-":
        Path(args.report).parent.mkdir(parents=True, exist_ok=True)
        Path(args.report).write_text(json.dumps(report, indent=1) + "\n")

    for r in results:
        status = "PASS" if r.ok else "FAIL"
        if not args.quiet or not r.ok:
            print(f"{status}  {r.path}: {r.n_verified}/{r.n_claims} numeric claims verified"
                  + (f", {len(r.issues)} issue(s)" if r.issues else ""))
        for i in r.issues:
            print(f"      line {i.line} [{i.kind}] {i.text!r}: {i.detail}")
    n_claims = sum(r.n_claims for r in results)
    n_ok = sum(r.n_verified for r in results)
    print(f"verify: {'OK' if ok else 'FAILED'} | {sum(r.ok for r in results)}/{len(results)} memos pass | "
          f"{n_ok}/{n_claims} claims verified against facts.json {reg.sha256[:12]}"
          + ("" if now else " | wall-clock freshness not checked (snapshot registry)"))
    return 0 if ok else 1


def _rel(p: Path) -> str:
    try:
        return str(Path(p).resolve().relative_to(ROOT))
    except ValueError:
        return str(p)


if __name__ == "__main__":
    sys.exit(main())
